### ISSUE TITLE
Дизайн landing page

### ISSUE THREAD

**Issue by s0b0lev** [maddevsio/heimdall#14]
### Описание
Сканнер эфириум смарт контрактов на предмет известных нарушней безопасности.

Название проекта heimdall, это [персонаж marvel ](https://en.wikipedia.org/wiki/Heimdall_(comics)) (также известный как Наблюдатель миров (англ. The Watcher of Worlds) — всевидящий и всеслышащий Асгардиец). Типа наш сканнер как Хеймдалль следит за смарт контрактами эфировскими.

Для анализа на текущий момент используется инструмент: [mythril](https://github.com/ConsenSys/mythril)

Список инструментов будет пополняться.

### Основные фичи сервиса
1. Иконка (badge) состояния смарт контрактов в гитхаб репозитории ([пример иконки](http://mythril.s0b0lev.com/badge/github/maddevsio/neureal-token-test))
2. Отчет по состоянию смарт контрактов в репозитории ([пример отчета](http://mythril.s0b0lev.com/report/github/maddevsio/neureal-token-test))

### Содержание лендинг пейджа
- Сайт будет на английском
- Картинка с Хеймдаллем
- Фон звездный (или с нодами, типа линии с точками)
- Название сервиса:
  - **title:** Heimdall
  - **subtitle:** Smart Contracts Security Monitoring
- В центр форма с текстовым полем, туда вводится урл репозиторий
- Кнопка - получить badge
- По клику на кнопку отображается код, который необходимо вставить в README.md гитхаба
- Ниже (футер) область с используемыми инструментами, сейчас пока только mythril можно указать

**Comment by puzanov** [comment]
Не хватает слогана. Smart Contracts Security Monitoring
